parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
scenarios:
- ""
postoverflows:
- ""
log_file: synapse-logs.log
log_type: syslog
labels: {}
ignore_parsers: false
override_statics: []
